name: Deno Test

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:
    inputs:
      page-root-directory:
        description: Page root directory
        default: './src/client/'
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      deno-version: v1.x

    steps:      
      - name: Setup Repository (${{github.event.repository.name}})
        uses: actions/checkout@v3

      - name: Setup Deno (${{env.deno-version}})
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{env.deno-version}}

      - name: Run linter
        run: deno lint
      
      - name: Run tests
        if: success() || failure()
        run: |
          mkdir reports
          deno test -A --unstable --check --reload --doc --allow-none --junit-path="./report.xml"
      
      - name: Report tests (report.xml)
        uses: dorny/test-reporter@v1
        with:
          name: Deno Test Report
          path: ./report.xml
          reporter: jest-junit
